### ISSUE TITLE
Change exchange intention id to random number

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/hack.HydraDX-node#10]
Let's discard this storage item and use randomly generated hash so that this never overflows.

@orca84 is going to have a look at this.

https://github.com/galacticcouncil/hack.HydraDX-node/blob/694291f74180a4755904a6aa75a3ea4fbfb8ab0e/pallets/exchange/src/lib.rs#L48

**Comment by enthusiastmartin** [comment]
Can we do this in a way it is easily mockable in tests ? 

In exchange pallet there are ( or will be soon) tests of events, so it should be possible to determine a value for intention id easily. 

So for example, instead of the hash,  it will be possible to change it in tests  so it will be generate sequential numbers like it does now.

**Comment by jak-pan** [comment]
@enthusiastmartin Do you have any proposal? Is it possible for you to get intention id hash from the first item event you receive?

**Comment by enthusiastmartin** [comment]
@jak-pan although  we talked a possible way ( using a trait which would be implemented differently for tests ) - now that i am thinking about it- it wont be probably possible. Since the intention id is part of the event itself and it is defined as 'hash type' . 

so, it wont be possible to change a type ( unless someone has another idea )

I will think about it again

but perhaps ,getting the hash from the last event is easier.

**Comment by jak-pan** [comment]
Intention Id itself could be a configurable trait in primitives/runtime like balance or accountId but that might be an overkill if it's only used for UI?
