### ISSUE TITLE
Automatic benchmarking

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/hack.HydraDX-node#57]

**Comment by enthusiastmartin** [comment]
Hydra-bench-bot is set up and running. It is possible to run bench for selected pallet using a special command in PR's comment.

**Comment by jak-pan** [comment]
Do we want to auto-bench when pushed to master?

**Comment by enthusiastmartin** [comment]
> Do we want to auto-bench when pushed to master?

No, i dont think it is needed. Because lot of time - new changes wont have impact on the actual performance. And it would need bot adjustments too as it is configured to work with PRs. 

So i would leave it on a developer to run benchmarks when needed and have the new weights committed along the new changes he/she has done.

**Comment by jak-pan** [comment]
Sounds reasonable. Closing
